# Basic
title: Eya GARCI
subtitle: Artificial Intelligence Developer
description: Welcome to my blog!
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Eya GARCI
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Personal Blog
url: "https://eyagarci.github.io/"

# Comment
comment:
    # disqus: leopard
    # # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: 5366874726
    github: eyagarci
    mail: garci.eya@gmail.com

# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 4cee09928f6efaba04655ffd61981950

# # Google Analytics
# # ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: UA-84134159-3
#     host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home page

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}
    - {title: Blog, description: tags, url: '/tags'}
    - {title: Resume, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
